# Analise Preditiva de churn

## Sobre o Dataset

Para o nosso projeto usaremos uma base de churn,  essa base se diz respeito a serviços de internet, telefone e tv - Telecomunicação.

Vamos realizar aqui as EDA.

Legenda dos dados:

*   **CustomerID** : Esse é o ID único de cada cliente nosso da rede de produtos de telecomunicação.

*   **Genero** : O genero dos nossos clientes.

*   **Idoso** : Se nosso cliente tem acima de 60 anos ou não. (Sim = 1 | Não = 0)

*   **Casado** : Se nosso cliente é casado ou não.

*   **Dependents** : Se cliente tem dependentes.

*   **Tempo_como_Cliente** : Tempo em meses que nosso cliente está com a nossa empresa.

*   **PhoneService** : Se ele contratou serviço telefônico com a nossa empresa.

*   **Servico_Internet** : Qual o tipo de serviço de internet contratado.

*   **Servico_Seguranca** : Se ele contratou serviço de segurança com a nossa empresa.

*   **Suporte_Tecnico** : Se já acionou o suporte técnico.

*   **StreamingTV** : Se ele contratou serviço de streaming para TV.

*   **Tipo_Contrato** : Qual o tipo de contrato dos nossos clientes, se era mensal, anual etc.

*   **Tipo_Contrato** : Qual o tipo de contrato dos nossos clientes, se era mensal, anual etc.

*   **PaymentMethod** : Forma de Pagamento.

*   **Pagamento_Mensal** : Quanto o cliente pagava mensalmente.

*   **Total_Pago** : Total já pago pelo cliente para nossa companhia.

*   **Churn** : Nossa coluna mais importante, se nosso cliente nos abandonou ou não.

## Objetivo

## Ferramentas

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
df = pd.read_csv("data.csv", delimiter=';')

df.head(10)

,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,PhoneService,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),NaN,1840.75,No
4,9237-HQITU,NaN,0,No,No,2,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,NaN,151.65,Yes
5,9305-CDSKC,NaN,0,No,No,8,Yes,Fiber optic,No,No,Yes,Month-to-month,Electronic check,NaN,820.50,NaN
6,1452-KIOVK,NaN,0,No,Yes,22,Yes,Fiber optic,No,No,Yes,Month-to-month,Credit card (automatic),NaN,1949.40,NaN
7,6713-OKOMC,NaN,0,No,No,10,No,DSL,Yes,No,No,Month-to-month,Mailed check,NaN,301.90,NaN
8,7892-POOKP,NaN,0,Yes,No,28,Yes,Fiber optic,No,Yes,Yes,Month-to-month,Electronic check,NaN,3046.05,NaN
9,6388-TABGU,NaN,0,No,Yes,62,Yes,dsl,Yes,No,No,One year,Bank transfer (automatic),NaN,3487.95,NaN

# Etapa 1 - EDA

In [4]:
#seu código aqui
df.dtypes

customerID                str
Genero                    str
Idoso                   int64
Casado                    str
Dependents                str
Tempo_como_Cliente      int64
PhoneService              str
Servico_Internet          str
Servico_Seguranca         str
Suporte_Tecnico           str
StreamingTV               str
Tipo_Contrato             str
PaymentMethod             str
Pagamento_Mensal      float64
Total_Pago            float64
Churn                     str
dtype: object

In [5]:
colunas = ['Idoso', 'Casado', 'Dependents', 'Churn']

for i in colunas:
    df[i] = df[i].astype(bool)

In [6]:
df.dtypes

customerID                str
Genero                    str
Idoso                    bool
Casado                   bool
Dependents               bool
Tempo_como_Cliente      int64
PhoneService              str
Servico_Internet          str
Servico_Seguranca         str
Suporte_Tecnico           str
StreamingTV               str
Tipo_Contrato             str
PaymentMethod             str
Pagamento_Mensal      float64
Total_Pago            float64
Churn                    bool
dtype: object

In [7]:
df.isnull().mean()*100

customerID             0.00
Genero                 0.48
Idoso                  0.00
Casado                 0.00
Dependents             0.00
Tempo_como_Cliente     0.00
PhoneService          59.28
Servico_Internet       0.00
Servico_Seguranca      0.00
Suporte_Tecnico        0.00
StreamingTV            0.00
Tipo_Contrato          0.00
PaymentMethod          0.00
Pagamento_Mensal      13.00
Total_Pago             0.00
Churn                  0.00
dtype: float64

In [8]:
df.describe()

       Tempo_como_Cliente  Pagamento_Mensal   Total_Pago
count         2500.000000       2175.000000  2500.000000
mean            32.341600         65.607563  2291.882880
std             24.626398         29.931520  2265.347752
min              0.000000         18.400000    18.800000
25%              8.000000         39.500000   402.337500
50%             29.000000         71.450000  1405.325000
75%             56.000000         90.250000  3867.162500
max             72.000000        118.650000  8564.750000

### Tratamento de dados nulos

Optei por deletar a coluna [PhoneService],  pois aferindo que nao possui relevancia significativa para a nossa analise, alem disso se trata de uma coluna boleana, por padrao os dados nulos seriam preenchidos com false, mas isso tornaria minha analise enviesada e com possiveis outliers pelo alta quantidade de dados nulos.

In [63]:
df['PhoneService'].unique()

array(['No', 'Yes', nan], dtype=object)

In [58]:
df.drop('PhoneService', axis=1)

,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,7590-VHVEG,Female,False,True,True,1,DSL,No,No,No,Month-to-month,Electronic check,29.850000,29.85,True
1,5575-GNVDE,Male,False,True,True,34,DSL,Yes,No,No,One year,Mailed check,56.950000,1889.50,True
2,3668-QPYBK,Male,False,True,True,2,DSL,Yes,No,No,Month-to-month,Mailed check,53.850000,108.15,True
3,7795-CFOCW,Male,False,True,True,45,DSL,Yes,Yes,No,One year,Bank transfer (automatic),65.607563,1840.75,True
16,8191-XWSZG,F,False,True,True,52,No,No internet service,No internet service,No internet service,One year,Mailed check,65.607563,1022.95,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,6188-UXBBR,Female,False,True,True,38,No,No internet service,No internet service,No internet service,One year,Credit card (automatic),20.250000,814.75,True
2496,2333-KWEWW,Male,False,True,True,18,No,No internet service,No internet service,No internet service,Two year,Credit card (automatic),20.050000,388.60,True
2497,5702-SKUOB,Female,False,True,True,4,No,No internet service,No internet service,No internet service,Month-to-month,Mailed check,19.600000,93.45,True
2498,1134-YWTYF,Male,False,True,True,27,DSL,No,Yes,No,Month-to-month,Electronic check,53.800000,1389.85,True
2499,6061-GWWAV,Male,False,True,True,41,DSL,Yes,No,Yes,One year,Mailed check,70.200000,2894.55,True

Indo para a coluna [Pagamento mensal] podemos observar que se trata de uma coluna com poucos dados faltantes, representando 13% de todo conjunto, e a media nao e discrepante em relacao aos valores maximos e minimos como pudemos observar pela funcao describe. Por se tratar de uma coluna importante para analise, pois o pagamento pode influenciar na presenca ou saida do cliente optei por preencher os valores nulos pela media da coluna.

In [9]:
df['Pagamento_Mensal'].describe()
df['Pagamento_Mensal'] = df['Pagamento_Mensal'].fillna(df['Pagamento_Mensal'].mean())

Sobre a coluna [Genero] ela tem um numero insigficante de valores nulos representando apenas 0.48% isso equivalore a apenas 12 linhas. Logo aferi que a quantidade de valores nulos e extremamente insignificante na coluna genero, alem disso nao se trata de uma analise que o genero impacta substancialmente, por isso optei em apagar as linhas que contem os valores nulos.

In [10]:
df = df.dropna(subset=['Genero'])
df['Genero'].isnull().sum()

np.int64(0)

In [ ]:
# Padronizando os valores categoricos
df['Genero'].unique()
mapa = {'Female' : 'F', 'Male': 'M', 'f': 'F'}
df['Genero'] = df['Genero'].map(mapa)

In [11]:
# Padronizando colunas
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
)

In [12]:
df

,customerid,genero,idoso,casado,dependents,tempo_como_cliente,phoneservice,servico_internet,servico_seguranca,suporte_tecnico,streamingtv,tipo_contrato,paymentmethod,pagamento_mensal,total_pago,churn
0,7590-VHVEG,Female,False,True,True,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.850000,29.85,True
1,5575-GNVDE,Male,False,True,True,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.950000,1889.50,True
2,3668-QPYBK,Male,False,True,True,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.850000,108.15,True
3,7795-CFOCW,Male,False,True,True,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),65.607563,1840.75,True
16,8191-XWSZG,F,False,True,True,52,Yes,No,No internet service,No internet service,No internet service,One year,Mailed check,65.607563,1022.95,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,6188-UXBBR,Female,False,True,True,38,Yes,No,No internet service,No internet service,No internet service,One year,Credit card (automatic),20.250000,814.75,True
2496,2333-KWEWW,Male,False,True,True,18,Yes,No,No internet service,No internet service,No internet service,Two year,Credit card (automatic),20.050000,388.60,True
2497,5702-SKUOB,Female,False,True,True,4,Yes,No,No internet service,No internet service,No internet service,Month-to-month,Mailed check,19.600000,93.45,True
2498,1134-YWTYF,Male,False,True,True,27,Yes,DSL,No,Yes,No,Month-to-month,Electronic check,53.800000,1389.85,True
2499,6061-GWWAV,Male,False,True,True,41,Yes,DSL,Yes,No,Yes,One year,Mailed check,70.200000,2894.55,True